language: rust
script: cargo build --verbose && cargo test --verbose
rust:
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - 1.7.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
branches:
  except:
    - /^issue-.*$/
