[package]
name = "cargo-script"
version = "0.1.1"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[dependencies]
env_logger = "0.3.1"
flate2 = "0.2.7"
log = "0.3.1"
rustc-serialize = "0.3.14"
shaman = "0.1.0"
toml = "0.1.20"

[dependencies.clap]
version = "0.10.2"

# Disable the "color" feature because it just outputs garbage on Windows.
default-features = false
features = ["suggestions"]

[target.i686-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.0"
winapi = "0.1.19"
uuid-sys = "0.1.1"

[target.x86_64-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.0"
winapi = "0.1.19"
uuid-sys = "0.1.1"
