[package]
name = "cargo-script"
version = "0.2.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

description = "A Cargo subcommand designed to let people quickly and easily run Rust \"scripts\" which can make use of Cargo's package ecosystem."
repository = "https://github.com/DanielKeep/cargo-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]

build = "build.rs"

exclude = [
    "scripts/*",
    ".travis.yml",
]

[dependencies]
clap = "2.9.2"
env_logger = "0.3.1"
hoedown = "3.0.3"
lazy_static = "0.1.15"
log = "0.3.1"
regex = "0.1.44"
rustc-serialize = "0.3.16"
shaman = "0.1.0"
time = "0.1.25"
toml = "0.1.20"

[target.i686-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.i686-pc-windows-msvc.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.x86_64-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[target.x86_64-pc-windows-msvc.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2" # WARNING: do not use with rustc < 1.15
winapi = "0.2.8"

[dev-dependencies]
gcc = "0.3"
scan-rules = "0.1.3"
tempdir = "0.3.4"

[build-dependencies]
rustc_version = "0.1.4"

[profile.release]
lto = true
