allowed-duplicate-crates = [
	"getrandom",
	"wasi",
	"windows_aarch64_gnullvm",
	"windows_aarch64_msvc",
	"windows_i686_gnu",
	"windows_i686_gnullvm",
	"windows_i686_msvc",
	"windows-sys",
	"windows-targets",
	"windows_x86_64_gnu",
	"windows_x86_64_gnullvm",
	"windows_x86_64_msvc",
]
